version: "3.8"
services:
  echoip:
    image: mpolden/echoip
    command: >
      -p
      -r
      -H X-Forwarded-For
      -a /data/GeoLite2-ASN.mmdb
      -c /data/GeoLite2-City.mmdb
      -f /data/GeoLite2-Country.mmdb
    ports:
      - "8001:8080"
    volumes:
      - "./wookingwoo_data/GeoLite2:/data"
    restart: unless-stopped

# docker-compose -f docker-compose.yml up
